### ISSUE TITLE
这个效率和其他beanutils比较如何？

### ISSUE THREAD

**Issue by kaitezhan** [houbb/bean-mapping#1]
如题，想知道up主的答案，谢谢

**Comment by kaitezhan** [comment]
这个效率和其他beanutils比较如何？

**Comment by houbb** [comment]
比较常见的几种映射框架：
1. apache BeanUtils
2. spring BeanUtils
3. dozer 

性能和 spring 差不多，比 apache 好。当然和 dozer 比，没有其成熟。

我写这个工具出于以下目的：
（1）目前的赋值框架没有 conditon，也就是满足什么条件才能赋值。这个框架解决了。
（2）自己写一遍，也便于优化。中间尝试过加 cache，感觉性能提升不大，就去掉了。
（3）学习目的。

**Comment by houbb** [comment]
> 如题，想知道up主的答案，谢谢

参见 [性能对比图](https://github.com/houbb/bean-mapping#%E6%80%A7%E8%83%BD)
